name: golang-pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.3  # Обновлено до 1.24

  steps:
  - uses: actions/checkout@v4
  - name: Install dependencies
    run: go mod download  # ← Новый шаг
  - name: Run Unit Tests
    run: go test ./...