name: golang-pipeline  # Название workflow

# Запускаем при каждом push в любую ветку
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest  # Используем свежий Ubuntu
    container: golang:1.22  # Берём официальный образ Go 1.22

    steps:
      # Шаг 1: Клонируем репозиторий
      - uses: actions/checkout@v4

      # Шаг 2: Запускаем unit-тесты
      - name: Run Unit Tests
        run: go test ./...

      # Шаг 3: Проверяем код через go vet
      - name: Vet
        run: go vet ./...